# Generated by Django 2.2.19 on 2021-10-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211010_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='any_slug', max_length=100),
        ),
    ]
